info_dict={
    "王力鸿":{
        "部门":"科技部",
        "工资":3000,
        "级别":1,
    },
    "周杰轮":{
        "部门":"市场部",
        "工资":5000,
        "级别":3,
    },
    "林俊节":{
        "部门":"市场部",
        "工资":7000,
        "级别":2,
    },
    "张学油":{
        "部门":"科技部",
        "工资":4000,
        "级别":1,
    },
    "刘德滑":{
        "部门":"市场部",
        "工资":6000,
        "级别":2,
    }
}
print(f"员工在升职加薪之前的结果是:{info_dict}")
for name in info_dict:
    if info_dict[name]["级别"]==1:
        employee_info_dict=info_dict[name]
        employee_info_dict["级别"]=2
        employee_info_dict["工资"]+=1000
        info_dict[name]=employee_info_dict
print(f"对员工进行升职加薪后的结果是：{info_dict}")